### ISSUE TITLE
LED Custom Palette does not work with Kaleidoscope-Bundle-Keyboardio repo

### ISSUE THREAD

**Issue by bjarkegosvig** [jukben/keyboardio-led-custom-palette#5]
Hi
I have cloned the new Kaleidoscope-Bundle-Keyboardio repo and tried to use it with LED Custom Palette release 1.1.0  and I can't make it work. At one point since release 1.1.0  the Focus plugin was replaced with another plugin called [FocusSerial](https://github.com/keyboardio/Kaleidoscope/blob/master/doc/plugin/FocusSerial.md). In FocusSerial hooks are not used anymore. 

I have tried to modify your example sketch to use FocusSerial, but the result is that  LED Custom Palette recognize my model 01 but when I give a key a color and presses synchronize Led Custum Palette says "everything Ok" but nothing happens on the keyboard. You can see my modified example sketch at https://github.com/bjarkegosvig/Model01-Firmware/blob/ledPalette/Model01-Firmware.ino

I hope you can give me some pointer on how to make LED Custom Palette work with the new FocusSerial plugin

**Comment by jukben** [comment]
Oh man, I'd love to help you, because I'm super happy that there is someone using it. Unfortunately, I sold my Keyboardio because it didn't fit in my workflow. 😢 

This part is responsible for getting initial data
https://github.com/jukben/keyboardio-led-custom-palette/blob/master/src/renderer/Provider.js#L83

This part is responsible for syncing the colors
https://github.com/jukben/keyboardio-led-custom-palette/blob/master/src/renderer/Provider.js#L201

> If you run app in development, you can access the console to see the errors / console.logs

But it's weird because as you don't get an error, it means that the serial response is OK (`.` is returned) 🤔 

The plugin also using https://github.com/keyboardio/Kaleidoscope-Colormap, which is right now archived as well. Commands provided by this package are crucial.

Hey @algernon, could you help us? 🙏 I'd appreciated it and since you've been able to run it already it could be without any hassle. 

Another option would be just to downgrade. 😞 

Sorry I can help you more.

**Comment by algernon** [comment]
The protocol should have remained the same, I'll have a look. (Colormap, and the rest of the plugins, have been merged into the main Kaleidoscope repo, by the way)

The sketch linked in the original report *looks* correct to me.

**Comment by algernon** [comment]
A few questions @bjarkegosvig, if I may:

- When you're trying to use this application, is your Model01 set to the Colormap LED effect, or is LEDOff active? (the sketch sets LEDOff as active, but you might have switched.) It will only work if you have the `ColormapEffect` plugin active. Changes are recorded otherwise too, but the results are only displayed if that mode is active.

- What operating system are you on? I've seen issues on OSX with serial communication, which might result in garbage being sent or read from the keyboard. keyboardio/Kaleidoscope-Bundle-Keyboardio#7 should help with that. (This was a problem present previously too, mind you.)

I just tried reproducing the problem under Debian, and it Works For Me™...

**Comment by bjarkegosvig** [comment]
Doh it was the active LedOff that I missed :flushed: Thank you both very much for the help, everything works perfect when activate the led effects. 
I guess I need some sleep

**Comment by jukben** [comment]
Haha. Glad it's working! 

Thanks for your support @algernon 

Enjoy @bjarkegosvig and share your layout somewhere 👍
